### ISSUE TITLE
Gas price calculation issues

### ISSUE THREAD

**Issue by alerdenisov** [backmeupplz/transfer-eth#1]
https://github.com/backmeupplz/transfer-eth/blob/b1de0a2d2fa5e216830d1eb45b69606a2185ca90/index.js#L71

It's not a great approach to set up gas price. 

Take a look at special method inside `web3`: https://web3js.readthedocs.io/en/1.0/web3-eth.html#getgasprice

**Comment by alerdenisov** [comment]
Oh. Sorry man. I just noticed about API call to gas station. It's already fine but depends on external service.

**Comment by backmeupplz** [comment]
Np, thanks for noticing though :)
