### ISSUE TITLE
Gas limit calculation issue

### ISSUE THREAD

**Issue by alerdenisov** [backmeupplz/transfer-eth#2]
https://github.com/backmeupplz/transfer-eth/blob/b1de0a2d2fa5e216830d1eb45b69606a2185ca90/index.js#L72

The gas limit shouldn't be constant. If you're focused only on transfer ether between EOAs it should be lower to prevent side effects (exactly 21000) or calculated in runtime with special RPC call: https://web3js.readthedocs.io/en/1.0/web3-eth.html#estimategas

Also, great practice to get a code before transfer to check if the receiver is a contract and send a warning to the sender. Take a look at `getCode` method: https://web3js.readthedocs.io/en/1.0/web3-eth.html#getcode

**Comment by backmeupplz** [comment]
Thank you a lot for the suggestion! Addressing both issues one-by-one:

1. I lowered the gas limit to 21k as per suggestion, however I think it will be sufficient for the small group of people using this transfer method
2. As well as this group of people should be able to verify whether the recipient is a smart contract.

Cheers!
